### ISSUE TITLE
Choosing any input for one grid

### ISSUE THREAD

**Issue by mohammalmokdad** [simonavrillon/I-Spin#1]
Good afternoon,

In the lab, we use the Multiple Input 2 as our primary input for our electrode grid. However, the way the program is set up only allow Multiple Input 2 to be active if Multiple Input 1 is active. Is it possible that the user can select ANY combination of grids being on or off and the program still work? For example, if input 2 and 4 are the ones which work on the quattrocento, the user should be able to get the data from them. Trying to manually make grid 1 read from input 2 gives many errors due to the data and EMG vectors being hard coded to follow the specific order. 

With this feature, the lab will not be restricted to only using a worse performing input as the primary grid.

**Comment by mohammalmokdad** [comment]
Looking deeper into the code, I see that it is hard-coded to only accept the 64 grid electrodes in a very specific configuration. I think allowing different electrode sizes for different inputs (i.e. not hardcoding the electrodes and making it dynamic) would be an excellent feature for the versatility of the software.

**Comment by simonavrillon** [comment]
Hi @mohammalmokdad 
in the last version of ISpin_Quattrocento, you can select any specific input and choose between different grids. This should give you more flexibility to adapt to your experimental setting.
